### ISSUE TITLE
map_figures.R: Error in join(pixels, year) : could not find function "join"

### ISSUE THREAD

**Issue by MatthieuStigler** [AlbertogGarcia/defor_econometrics_replication#1]
Hi Alberto

I was curious to try your code, but I ran into an issue with `map_figures.R`, even when using with `renv`:

> Error in join(pixels, year) : could not find function "join"

Side note, there's also a warning earlier on:

> countyscape = full_landscape(nobs, cellsize, ppoints, cpoints)
Warning message:
In matrix(value, n, p) :
  data length [28125] is not a sub-multiple or multiple of the number of columns [4]

Thanks!

**Comment by AlbertogGarcia** [comment]
Yes that's it! The fabricatr package changed the function and I fixed it the lazy way, which caused the problem in map_figures.R
